# Generated by Django 6.1.1 on 2026-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('teacher', models.CharField(max_length=200)),
                ('students', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
            ],
        ),
    ]
