# Generated by Django 6.1.1 on 2026-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_first_name_and_more'),
        ('classrooms', '0003_classroom_student_alter_classroom_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_classrooms', to='accounts.userprofile'),
        ),
    ]
