# Generated by Django 6.1.1 on 2026-10-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_first_name_and_more'),
        ('classrooms', '0004_remove_classroom_student_classroom_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom'),
        ),
    ]
